### ISSUE TITLE
About the streamline plot

### ISSUE THREAD

**Issue by YonghaoXu** [locuslab/gradient_regularized_gan#1]
Hi, Thank you for your sharing in this repo!
I have some questions about the streamline plot (Figure 3) in the paper. 

First, what is the goal that the GAN model is trying to achieve here? You mentioned that this is a 2D system where both the true and the latent distribution is uniform over ``[-1,1]``, but what is the real distribution here? Figure 1 seems more straightforward that the GAN model attempts to learn a mixture of eight Gaussians.

Second, what does the value in the streamline plot represent? The arrows seem to show the optimization routine of the parameter ``a`` and ``w2``.

Thank you for your time!

**Comment by vaishnavh** [comment]
Hey!
Thanks for reaching out.
The "real distribution" is what we call as the "true distribution" here, which is uniform over `[-1,1]`.  In other words, the distribution of $p_{data}$ is uniform in `[-1,1]`.

Yes, the streamline plot represents the trajectory of GAN optimization with infinitesimal step size, starting from different points in the neighborhood of the equilibrium. 

Feel free to let me know if you've more questions!

**Comment by YonghaoXu** [comment]
Thank you for your quick reply! I have two more questions now. 

The first one is about the equilibrium. In the paper, it is mentioned that the equilibrium is (0,1). I wonder if this equilibrium is manually selected or learned by the GAN model itself? Besides, under this setting, the discriminator would be ``D(x)=0`` with ``w2=0`` while the generator would be ``G(z)=z`` with ``a=1`` (correct me if I misunderstand it). How could this be the balanced condition for the GAN model at the end?

The second one is about the implementation of such streamline plots. I really like the streamline plot of the vanilla WGAN, where the trajectory goes in orbits, but I am not sure how to make it. An immature guess would be calculating the gradients with parameters ``(w2,a)`` at all meshgrid coordinates, and plot these gradients with the ``quiver`` function. Can you give some tips for this issue?

**Comment by vaishnavh** [comment]
Of course!

The equilibrium is given by the position in the parameter space where the gradient updates would be zero. For the given setup (with `D(x)=w2 x^2` and `G(z)=az` and a real distribution uniform over `[-1,1]`), `(0,1)` is an equilibrium point. To verify this, you need to calculate the gradient of `V` with respect to `w2` and `a` and check if they are zero at `(0,1)`. Here's the calculation: 
`V(w2, a) = int_{-1}^{+1} 0.5 f(w2  x^2)  dx  + int_{-1}^{1} 0.5 f(-w2  (az)^2)  dz `
Therefore the derivative of V w.r.t. w2 would be `int_{-1}^{+1} 0.5 f'(w2  x^2)  x^2 dx  - int_{-1}^{1} 0.5 f'(-w2  (az)^2) (az)^2  dz`. At `(0,1)` the two integrals become identical, so they cancel out each other to become zero.
As for the derivative of V w.r.t. a, it would be ` int_{-1}^{1} 0.5 f'(-w2  (az)^2) * -w2 * z^2 * 2a  dz` which is zero when `w2=0`. Hence `(0,1)` is an equilibrium.

For the streamline plots we used Wolfram Mathematica's `StreamPlot`. Have you tried Matplotlib's `Streamplot` (https://matplotlib.org/3.1.1/gallery/images_contours_and_fields/plot_streamplot.html)? I've not used it but it seems like it should achieve the same thing.

**Comment by YonghaoXu** [comment]
Thank you for your detailed reply! 

It helps me a lot. I would try to digest your comments now.
